spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/user_db
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
server:
  port: 9001
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
