server:
  port: 9080

spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: inventoryServiceCircuitBreaker
#                fallbackUri: forward:/fallback/inventory
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
#          filters:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
#          filters:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: customerServiceCircuitBreaker
#                fallbackUri: forward:/fallback/customers
#            - name: Retry
#              args:
#                retries: 2
#                methods: GET
#                statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,INTERNAL_SERVER_ERROR
#                backoff:
#                  firstBackoff: 50ms
#                  maxBackoff: 500ms
#                  factor: 2
#                  basedOnPreviousValue: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
