spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_db
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}

server:
  port: 9002
  servlet:
    context-path: /api/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
