spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9004
  servlet:
    context-path: /api

application:
  kafka:
    topics:
      payment-events: payment-events
      payment-events-dlq: payment-events-dlq

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

