spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:9999

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
